#
# Identity Security Cloud API - IAI Role Mining
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<<<<<<<< HEAD:PSSailpoint/iai-role-mining/tests/Model/Roleminingpotentialroleref.Tests.ps1
Describe -tag 'PSSailpoint.IaiRoleMining' -name 'Roleminingpotentialroleref' {
    Context 'Roleminingpotentialroleref' {
        It 'Initialize-Roleminingpotentialroleref' {
            # a simple test to create an object
            #$NewObject = Initialize-Roleminingpotentialroleref -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType Roleminingpotentialroleref
========
Describe -tag 'PSSailpoint.V2026' -name 'V2026SourceDatasetResourcesInner' {
    Context 'V2026SourceDatasetResourcesInner' {
        It 'Initialize-V2026SourceDatasetResourcesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-V2026SourceDatasetResourcesInner -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType SourceDatasetResourcesInner
>>>>>>>> main:PSSailpoint/triggers/tests/Model/SourceDatasetResourcesInner.Tests.ps1
            #$NewObject.property | Should -Be 0
        }
    }
}
