#
# IdentityNow Beta API
# Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Changes
No description available.
.PARAMETER EventType
the event type
.PARAMETER IdentityId
the identity id
.PARAMETER Dt
the date of event
.OUTPUTS

AttributesChanged<PSCustomObject>
#>

function Initialize-BetaAttributesChanged {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Changes},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EventType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IdentityId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Dt}
    )

    Process {
        'Creating PSCustomObject: PSSailpointBeta => BetaAttributesChanged' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "changes" = ${Changes}
            "eventType" = ${EventType}
            "identityId" = ${IdentityId}
            "dt" = ${Dt}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AttributesChanged<PSCustomObject>

.DESCRIPTION

Convert from JSON to AttributesChanged<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AttributesChanged<PSCustomObject>
#>
function ConvertFrom-BetaJsonToAttributesChanged {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpointBeta => BetaAttributesChanged' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BetaAttributesChanged
        $AllProperties = ("changes", "eventType", "identityId", "dt")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "changes"))) { #optional property not found
            $Changes = $null
        } else {
            $Changes = $JsonParameters.PSobject.Properties["changes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "eventType"))) { #optional property not found
            $EventType = $null
        } else {
            $EventType = $JsonParameters.PSobject.Properties["eventType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "identityId"))) { #optional property not found
            $IdentityId = $null
        } else {
            $IdentityId = $JsonParameters.PSobject.Properties["identityId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dt"))) { #optional property not found
            $Dt = $null
        } else {
            $Dt = $JsonParameters.PSobject.Properties["dt"].value
        }

        $PSO = [PSCustomObject]@{
            "changes" = ${Changes}
            "eventType" = ${EventType}
            "identityId" = ${IdentityId}
            "dt" = ${Dt}
        }

        return $PSO
    }

}

