#
# Identity Security Cloud Beta API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Extra attributes map(dictionary) for the task.

.PARAMETER QpocJobId
The id of qpoc job
.PARAMETER TaskStartDelay
the task start delay value
.OUTPUTS

LoadUncorrelatedAccountsTaskTaskAttributes<PSCustomObject>
#>

function Initialize-BetaLoadUncorrelatedAccountsTaskTaskAttributes {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${QpocJobId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TaskStartDelay}
    )

    Process {
        'Creating PSCustomObject: PSSailpointBeta => BetaLoadUncorrelatedAccountsTaskTaskAttributes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "qpocJobId" = ${QpocJobId}
            "taskStartDelay" = ${TaskStartDelay}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to LoadUncorrelatedAccountsTaskTaskAttributes<PSCustomObject>

.DESCRIPTION

Convert from JSON to LoadUncorrelatedAccountsTaskTaskAttributes<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

LoadUncorrelatedAccountsTaskTaskAttributes<PSCustomObject>
#>
function ConvertFrom-BetaJsonToLoadUncorrelatedAccountsTaskTaskAttributes {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpointBeta => BetaLoadUncorrelatedAccountsTaskTaskAttributes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BetaLoadUncorrelatedAccountsTaskTaskAttributes
        $AllProperties = ("qpocJobId", "taskStartDelay")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "qpocJobId"))) { #optional property not found
            $QpocJobId = $null
        } else {
            $QpocJobId = $JsonParameters.PSobject.Properties["qpocJobId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "taskStartDelay"))) { #optional property not found
            $TaskStartDelay = $null
        } else {
            $TaskStartDelay = $JsonParameters.PSobject.Properties["taskStartDelay"].value
        }

        $PSO = [PSCustomObject]@{
            "qpocJobId" = ${QpocJobId}
            "taskStartDelay" = ${TaskStartDelay}
        }

        return $PSO
    }

}

