#
# Identity Security Cloud Beta API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Task return details

.PARAMETER Name
Display name of the TaskReturnDetails
.PARAMETER AttributeName
Attribute the TaskReturnDetails is for
.OUTPUTS

TaskReturnDetails<PSCustomObject>
#>

function Initialize-BetaTaskReturnDetails {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AttributeName}
    )

    Process {
        'Creating PSCustomObject: PSSailpointBeta => BetaTaskReturnDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if (!$AttributeName) {
            throw "invalid value for 'AttributeName', 'AttributeName' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "attributeName" = ${AttributeName}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TaskReturnDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to TaskReturnDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TaskReturnDetails<PSCustomObject>
#>
function ConvertFrom-BetaJsonToTaskReturnDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpointBeta => BetaTaskReturnDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BetaTaskReturnDetails
        $AllProperties = ("name", "attributeName")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attributeName"))) {
            throw "Error! JSON cannot be serialized due to the required property 'attributeName' missing."
        } else {
            $AttributeName = $JsonParameters.PSobject.Properties["attributeName"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "attributeName" = ${AttributeName}
        }

        return $PSO
    }

}

