templateDir: ./sdk-resources/resources
packageName: PSSailpoint.V2024
packageVersion: 1.4.10
apiNamePrefix: V2024
apiVersion: v2024
companyName: SailPoint Technologies
packageGuid: 51EC9F24-1977-40CE-A990-D0186150E0A1
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
subModuleName: V2024
moduleImportPath: github.com/sailpoint-oss/golang-sdk/v2/api_v2024
funtionPrefix: V2024
files:
  developerSite_code_examples.mustache:
    templateType: APIDocs
    destinationFilename: developerSite_code_examples.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: Index.md
