#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Roles
No description available.
.OUTPUTS

SubmitRolesRequest<PSCustomObject>
#>

function Initialize-NERMSubmitRolesRequest {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Roles}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.NERM => NERMSubmitRolesRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "roles" = ${Roles}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SubmitRolesRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to SubmitRolesRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SubmitRolesRequest<PSCustomObject>
#>
function ConvertFrom-NERMJsonToSubmitRolesRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.NERM => NERMSubmitRolesRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NERMSubmitRolesRequest
        $AllProperties = ("roles")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "roles"))) { #optional property not found
            $Roles = $null
        } else {
            $Roles = $JsonParameters.PSobject.Properties["roles"].value
        }

        $PSO = [PSCustomObject]@{
            "roles" = ${Roles}
        }

        return $PSO
    }

}

