#
# Identity Security Cloud V2024 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2024
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Type of Reassignment Configuration.

.PARAMETER Priority
No description available.
.PARAMETER InternalName
No description available.
.PARAMETER InternalNameCamel
No description available.
.PARAMETER DisplayName
Human readable display name of the type to be shown on UI
.PARAMETER Description
Description of the type of work to be reassigned, displayed by the UI.
.OUTPUTS

ConfigType<PSCustomObject>
#>

function Initialize-V2024ConfigType {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Priority},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("accessRequests", "certifications", "manualTasks")]
        [PSCustomObject]
        ${InternalName},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ACCESS_REQUESTS", "CERTIFICATIONS", "MANUAL_TASKS")]
        [PSCustomObject]
        ${InternalNameCamel},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.V2024 => V2024ConfigType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "priority" = ${Priority}
            "internalName" = ${InternalName}
            "internalNameCamel" = ${InternalNameCamel}
            "displayName" = ${DisplayName}
            "description" = ${Description}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ConfigType<PSCustomObject>

.DESCRIPTION

Convert from JSON to ConfigType<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ConfigType<PSCustomObject>
#>
function ConvertFrom-V2024JsonToConfigType {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.V2024 => V2024ConfigType' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in V2024ConfigType
        $AllProperties = ("priority", "internalName", "internalNameCamel", "displayName", "description")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "priority"))) { #optional property not found
            $Priority = $null
        } else {
            $Priority = $JsonParameters.PSobject.Properties["priority"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "internalName"))) { #optional property not found
            $InternalName = $null
        } else {
            $InternalName = $JsonParameters.PSobject.Properties["internalName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "internalNameCamel"))) { #optional property not found
            $InternalNameCamel = $null
        } else {
            $InternalNameCamel = $JsonParameters.PSobject.Properties["internalNameCamel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "displayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["displayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        $PSO = [PSCustomObject]@{
            "priority" = ${Priority}
            "internalName" = ${InternalName}
            "internalNameCamel" = ${InternalNameCamel}
            "displayName" = ${DisplayName}
            "description" = ${Description}
        }

        return $PSO
    }

}

