#
# Identity Security Cloud V2024 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2024
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER PolicyId
The password policy Id.
.PARAMETER PolicyName
The name of the password policy.
.PARAMETER Selectors
No description available.
.OUTPUTS

PasswordPolicyHoldersDtoInner<PSCustomObject>
#>

function Initialize-V2024PasswordPolicyHoldersDtoInner {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PolicyId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PolicyName},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Selectors}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.V2024 => V2024PasswordPolicyHoldersDtoInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "policyId" = ${PolicyId}
            "policyName" = ${PolicyName}
            "selectors" = ${Selectors}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PasswordPolicyHoldersDtoInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to PasswordPolicyHoldersDtoInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PasswordPolicyHoldersDtoInner<PSCustomObject>
#>
function ConvertFrom-V2024JsonToPasswordPolicyHoldersDtoInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.V2024 => V2024PasswordPolicyHoldersDtoInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in V2024PasswordPolicyHoldersDtoInner
        $AllProperties = ("policyId", "policyName", "selectors")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "policyId"))) { #optional property not found
            $PolicyId = $null
        } else {
            $PolicyId = $JsonParameters.PSobject.Properties["policyId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "policyName"))) { #optional property not found
            $PolicyName = $null
        } else {
            $PolicyName = $JsonParameters.PSobject.Properties["policyName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "selectors"))) { #optional property not found
            $Selectors = $null
        } else {
            $Selectors = $JsonParameters.PSobject.Properties["selectors"].value
        }

        $PSO = [PSCustomObject]@{
            "policyId" = ${PolicyId}
            "policyName" = ${PolicyName}
            "selectors" = ${Selectors}
        }

        return $PSO
    }

}

