#
# IdentityNow V3 API
# Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum RequestableObjectType.

.DESCRIPTION

Enum represented the currently supported requestable object types. Additional values may be added in the future without notice.
#>

enum RequestableObjectType {
    # enum value: "ACCESS_PROFILE"
    ACCESS_PROFILE
    # enum value: "ROLE"
    ROLE
    # enum value: "ENTITLEMENT"
    ENTITLEMENT
}

