#
# Identity Security Cloud v2026 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2026
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.V2026' -name 'V2026InnerHit' {
    Context 'V2026InnerHit' {
        It 'Initialize-V2026InnerHit' {
            # a simple test to create an object
            #$NewObject = Initialize-V2026InnerHit -Query "TEST_VALUE" -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType InnerHit
            #$NewObject.property | Should -Be 0
        }
    }
}
