#
# Identity Security Cloud API - Entitlements
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ApprovalSchemes
Ordered list of approval steps for the access request. Empty when no approval is required.
.OUTPUTS

Entitlementrevocationrequestconfig<PSCustomObject>
#>

function Initialize-Entitlementrevocationrequestconfig {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ApprovalSchemes}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.EntitlementsV1 => Entitlementrevocationrequestconfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "approvalSchemes" = ${ApprovalSchemes}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Entitlementrevocationrequestconfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to Entitlementrevocationrequestconfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Entitlementrevocationrequestconfig<PSCustomObject>
#>
function ConvertFrom-JsonToEntitlementrevocationrequestconfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.EntitlementsV1 => Entitlementrevocationrequestconfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Entitlementrevocationrequestconfig
        $AllProperties = ("approvalSchemes")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "approvalSchemes"))) { #optional property not found
            $ApprovalSchemes = $null
        } else {
            $ApprovalSchemes = $JsonParameters.PSobject.Properties["approvalSchemes"].value
        }

        $PSO = [PSCustomObject]@{
            "approvalSchemes" = ${ApprovalSchemes}
        }

        return $PSO
    }

}

