#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.NERM' -name 'NERMNERMUserProfilesApi' {
    Context 'New-NERMUserProfiles' {
        It 'Test New-NERMUserProfiles' {
            #$TestResult = New-NERMUserProfiles -CreateUserProfilesRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-NERMUserProfile' {
        It 'Test Remove-NERMUserProfile' {
            #$TestResult = Remove-NERMUserProfile -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-NERMUserProfiles' {
        It 'Test Remove-NERMUserProfiles' {
            #$TestResult = Remove-NERMUserProfiles -CreateUserProfilesRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-NERMUserProfile' {
        It 'Test Get-NERMUserProfile' {
            #$TestResult = Get-NERMUserProfile -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-NERMUserProfiles' {
        It 'Test Get-NERMUserProfiles' {
            #$TestResult = Get-NERMUserProfiles -Limit "TEST_VALUE" -Offset "TEST_VALUE" -Order "TEST_VALUE" -UserId "TEST_VALUE" -NeAttributeId "TEST_VALUE" -ProfileId "TEST_VALUE" -RelationshipType "TEST_VALUE" -Metadata "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-NERMUserProfile' {
        It 'Test Update-NERMUserProfile' {
            #$TestResult = Update-NERMUserProfile -Id "TEST_VALUE" -SubmitUserProfileRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-NERMUserProfiles' {
        It 'Test Update-NERMUserProfiles' {
            #$TestResult = Update-NERMUserProfiles -CreateUserProfilesRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Submit-NERMUserProfile' {
        It 'Test Submit-NERMUserProfile' {
            #$TestResult = Submit-NERMUserProfile -SubmitUserProfileRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
