#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.NERM' -name 'NERMCreateFulfillmentActionRequest' {
    Context 'NERMCreateFulfillmentActionRequest' {
        It 'Initialize-NERMCreateFulfillmentActionRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NERMCreateFulfillmentActionRequest -WorkflowAction "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateFulfillmentActionRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
