#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.NERM' -name 'NERMCreateLoginWorkflowRequest' {
    Context 'NERMCreateLoginWorkflowRequest' {
        It 'Initialize-NERMCreateLoginWorkflowRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NERMCreateLoginWorkflowRequest -Workflow "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateLoginWorkflowRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
