#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.NERM' -name 'NERMPermission1' {
    Context 'NERMPermission1' {
        It 'Initialize-NERMPermission1' {
            # a simple test to create an object
            #$NewObject = Initialize-NERMPermission1 -RoleId "TEST_VALUE" -SubjectId "TEST_VALUE" -Value "TEST_VALUE" -Subject "TEST_VALUE"
            #$NewObject | Should -BeOfType Permission1
            #$NewObject.property | Should -Be 0
        }
    }
}
