#
# NERM API
# The NERM API accesss and modifies resources in your environment.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.NERM' -name 'NERMProfileSelectAction' {
    Context 'NERMProfileSelectAction' {
        It 'Initialize-NERMProfileSelectAction' {
            # a simple test to create an object
            #$NewObject = Initialize-NERMProfileSelectAction -WorkflowId "TEST_VALUE" -Description "TEST_VALUE" -Archived "TEST_VALUE"
            #$NewObject | Should -BeOfType ProfileSelectAction
            #$NewObject.property | Should -Be 0
        }
    }
}
