#
# Identity Security Cloud Beta API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Key
The template notification key.
.PARAMETER Medium
The notification medium. Has to be one of the following enum values.
.PARAMETER Locale
The locale for the message text.
.PARAMETER Context
A Json object that denotes the context specific to the template.
.PARAMETER RecipientEmailList
A list of override recipient email addresses for the test notification.
.PARAMETER CarbonCopy
A list of CC email addresses for the test notification.
.PARAMETER BlindCarbonCopy
A list of BCC email addresses for the test notification.
.OUTPUTS

SendTestNotificationRequestDto<PSCustomObject>
#>

function Initialize-BetaSendTestNotificationRequestDto {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Key},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("EMAIL", "SLACK", "TEAMS")]
        [String]
        ${Medium},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Locale},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Context},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${RecipientEmailList},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${CarbonCopy},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${BlindCarbonCopy}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.Beta => BetaSendTestNotificationRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "key" = ${Key}
            "medium" = ${Medium}
            "locale" = ${Locale}
            "context" = ${Context}
            "recipientEmailList" = ${RecipientEmailList}
            "carbonCopy" = ${CarbonCopy}
            "blindCarbonCopy" = ${BlindCarbonCopy}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SendTestNotificationRequestDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to SendTestNotificationRequestDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SendTestNotificationRequestDto<PSCustomObject>
#>
function ConvertFrom-BetaJsonToSendTestNotificationRequestDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.Beta => BetaSendTestNotificationRequestDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BetaSendTestNotificationRequestDto
        $AllProperties = ("key", "medium", "locale", "context", "recipientEmailList", "carbonCopy", "blindCarbonCopy")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "key"))) { #optional property not found
            $Key = $null
        } else {
            $Key = $JsonParameters.PSobject.Properties["key"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "medium"))) { #optional property not found
            $Medium = $null
        } else {
            $Medium = $JsonParameters.PSobject.Properties["medium"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "locale"))) { #optional property not found
            $Locale = $null
        } else {
            $Locale = $JsonParameters.PSobject.Properties["locale"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "context"))) { #optional property not found
            $Context = $null
        } else {
            $Context = $JsonParameters.PSobject.Properties["context"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recipientEmailList"))) { #optional property not found
            $RecipientEmailList = $null
        } else {
            $RecipientEmailList = $JsonParameters.PSobject.Properties["recipientEmailList"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "carbonCopy"))) { #optional property not found
            $CarbonCopy = $null
        } else {
            $CarbonCopy = $JsonParameters.PSobject.Properties["carbonCopy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blindCarbonCopy"))) { #optional property not found
            $BlindCarbonCopy = $null
        } else {
            $BlindCarbonCopy = $JsonParameters.PSobject.Properties["blindCarbonCopy"].value
        }

        $PSO = [PSCustomObject]@{
            "key" = ${Key}
            "medium" = ${Medium}
            "locale" = ${Locale}
            "context" = ${Context}
            "recipientEmailList" = ${RecipientEmailList}
            "carbonCopy" = ${CarbonCopy}
            "blindCarbonCopy" = ${BlindCarbonCopy}
        }

        return $PSO
    }

}

