#
# Identity Security Cloud V2025 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2025
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DatasetIds
List of dataset Ids to aggregate machine identities
.OUTPUTS

MachineIdentityAggregationRequest<PSCustomObject>
#>

function Initialize-V2025MachineIdentityAggregationRequest {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${DatasetIds}
    )

    Process {
        'Creating PSCustomObject: PSSailpoint.V2025 => V2025MachineIdentityAggregationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$DatasetIds) {
            throw "invalid value for 'DatasetIds', 'DatasetIds' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "datasetIds" = ${DatasetIds}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to MachineIdentityAggregationRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to MachineIdentityAggregationRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

MachineIdentityAggregationRequest<PSCustomObject>
#>
function ConvertFrom-V2025JsonToMachineIdentityAggregationRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpoint.V2025 => V2025MachineIdentityAggregationRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in V2025MachineIdentityAggregationRequest
        $AllProperties = ("datasetIds")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'datasetIds' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasetIds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'datasetIds' missing."
        } else {
            $DatasetIds = $JsonParameters.PSobject.Properties["datasetIds"].value
        }

        $PSO = [PSCustomObject]@{
            "datasetIds" = ${DatasetIds}
        }

        return $PSO
    }

}

