#
# Identity Security Cloud V2025 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2025
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum MembershipType.

.DESCRIPTION

An enumeration of the types of membership choices
#>

enum MembershipType {
    # enum value: "ALL"
    ALL
    # enum value: "FILTER"
    FILTER
    # enum value: "SELECTION"
    SELECTION
}

