#
# IdentityNow Beta API
# Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpointBeta' -name 'BetaBetaCertificationCampaignsApi' {
    Context 'Complete-BetaCampaign' {
        It 'Test Complete-BetaCampaign' {
            #$TestResult = Complete-BetaCampaign -Id "TEST_VALUE" -CompleteCampaignOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-BetaCampaign' {
        It 'Test New-BetaCampaign' {
            #$TestResult = New-BetaCampaign -Campaign "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-BetaCampaignTemplate' {
        It 'Test New-BetaCampaignTemplate' {
            #$TestResult = New-BetaCampaignTemplate -CampaignTemplate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-BetaCampaignTemplate' {
        It 'Test Remove-BetaCampaignTemplate' {
            #$TestResult = Remove-BetaCampaignTemplate -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-BetaCampaignTemplateSchedule' {
        It 'Test Remove-BetaCampaignTemplateSchedule' {
            #$TestResult = Remove-BetaCampaignTemplateSchedule -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-BetaCampaigns' {
        It 'Test Remove-BetaCampaigns' {
            #$TestResult = Remove-BetaCampaigns -DeleteCampaignsRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-BetaCampaignTemplate' {
        It 'Test New-BetaCampaignTemplate' {
            #$TestResult = New-BetaCampaignTemplate -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaActiveCampaigns' {
        It 'Test Get-BetaActiveCampaigns' {
            #$TestResult = Get-BetaActiveCampaigns -Detail "TEST_VALUE" -Limit "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE" -Filters "TEST_VALUE" -Sorters "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaign' {
        It 'Test Get-BetaCampaign' {
            #$TestResult = Get-BetaCampaign -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaignReports' {
        It 'Test Get-BetaCampaignReports' {
            #$TestResult = Get-BetaCampaignReports -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaignReportsConfig' {
        It 'Test Get-BetaCampaignReportsConfig' {
            #$TestResult = Get-BetaCampaignReportsConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaignTemplate' {
        It 'Test Get-BetaCampaignTemplate' {
            #$TestResult = Get-BetaCampaignTemplate -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaignTemplateSchedule' {
        It 'Test Get-BetaCampaignTemplateSchedule' {
            #$TestResult = Get-BetaCampaignTemplateSchedule -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-BetaCampaignTemplates' {
        It 'Test Get-BetaCampaignTemplates' {
            #$TestResult = Get-BetaCampaignTemplates -Limit "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE" -Sorters "TEST_VALUE" -Filters "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-BetaCampaignTemplate' {
        It 'Test Update-BetaCampaignTemplate' {
            #$TestResult = Update-BetaCampaignTemplate -Id "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-BetaReassignCampaign' {
        It 'Test Invoke-BetaReassignCampaign' {
            #$TestResult = Invoke-BetaReassignCampaign -Id "TEST_VALUE" -AdminReviewReassign "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Start-BetaCampaignRemediationScan' {
        It 'Test Start-BetaCampaignRemediationScan' {
            #$TestResult = Start-BetaCampaignRemediationScan -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Start-BetaCampaignReport' {
        It 'Test Start-BetaCampaignReport' {
            #$TestResult = Start-BetaCampaignReport -Id "TEST_VALUE" -Type "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-BetaCampaignReportsConfig' {
        It 'Test Set-BetaCampaignReportsConfig' {
            #$TestResult = Set-BetaCampaignReportsConfig -CampaignReportsConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Set-BetaCampaignTemplateSchedule' {
        It 'Test Set-BetaCampaignTemplateSchedule' {
            #$TestResult = Set-BetaCampaignTemplateSchedule -Id "TEST_VALUE" -Schedule "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Start-BetaCampaign' {
        It 'Test Start-BetaCampaign' {
            #$TestResult = Start-BetaCampaign -Id "TEST_VALUE" -ActivateCampaignOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-BetaCampaign' {
        It 'Test Update-BetaCampaign' {
            #$TestResult = Update-BetaCampaign -Id "TEST_VALUE" -RequestBody "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
