#
# Identity Security Cloud V2024 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2024
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER RequestType
No description available.
.PARAMETER ContainsDeny
No description available.
.PARAMETER CampaignId
No description available.
.PARAMETER CampaignStatus
No description available.
.OUTPUTS

TemplateSlackCustomFields<PSCustomObject>
#>

function Initialize-V2024TemplateSlackCustomFields {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RequestType},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContainsDeny},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CampaignId},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CampaignStatus}
    )

    Process {
        'Creating PSCustomObject: PSSailpointV2024 => V2024TemplateSlackCustomFields' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "requestType" = ${RequestType}
            "containsDeny" = ${ContainsDeny}
            "campaignId" = ${CampaignId}
            "campaignStatus" = ${CampaignStatus}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TemplateSlackCustomFields<PSCustomObject>

.DESCRIPTION

Convert from JSON to TemplateSlackCustomFields<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TemplateSlackCustomFields<PSCustomObject>
#>
function ConvertFrom-V2024JsonToTemplateSlackCustomFields {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSailpointV2024 => V2024TemplateSlackCustomFields' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in V2024TemplateSlackCustomFields
        $AllProperties = ("requestType", "containsDeny", "campaignId", "campaignStatus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestType"))) { #optional property not found
            $RequestType = $null
        } else {
            $RequestType = $JsonParameters.PSobject.Properties["requestType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "containsDeny"))) { #optional property not found
            $ContainsDeny = $null
        } else {
            $ContainsDeny = $JsonParameters.PSobject.Properties["containsDeny"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "campaignId"))) { #optional property not found
            $CampaignId = $null
        } else {
            $CampaignId = $JsonParameters.PSobject.Properties["campaignId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "campaignStatus"))) { #optional property not found
            $CampaignStatus = $null
        } else {
            $CampaignStatus = $JsonParameters.PSobject.Properties["campaignStatus"].value
        }

        $PSO = [PSCustomObject]@{
            "requestType" = ${RequestType}
            "containsDeny" = ${ContainsDeny}
            "campaignId" = ${CampaignId}
            "campaignStatus" = ${CampaignStatus}
        }

        return $PSO
    }

}

