name: "Build PowerShell SDK"
description: "Build all API versions of the PowerShell SDK from OpenAPI specs"

inputs:
  api-specs-path:
    description: "Path to the checked-out api-specs repository"
    required: false
    default: "api-specs"
  skip-tests:
    description: "Skip running tests after building"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download OpenAPI Generator
      shell: bash
      run: |
        wget -q https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.12.0/openapi-generator-cli-7.12.0.jar -O openapi-generator-cli.jar

    - name: Run Prescript
      shell: bash
      run: node sdk-resources/prescript.js ${{ inputs.api-specs-path }}/idn

    - name: Build V3 SDK
      shell: bash
      run: |
        rm -rf ./PSSailpoint/v3
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v3.yaml \
          -g powershell -o PSSailpoint/v3 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v3-config.yaml
        node sdk-resources/postscript.js ./PSSailpoint/v3

    - name: Build Beta SDK
      shell: bash
      run: |
        rm -rf ./PSSailpoint/beta
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.beta.yaml \
          -g powershell -o PSSailpoint/beta \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/beta-config.yaml
        node sdk-resources/postscript.js ./PSSailpoint/beta

    - name: Build V2024 SDK
      shell: bash
      run: |
        rm -rf ./PSSailpoint/v2024
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2024.yaml \
          -g powershell -o PSSailpoint/v2024 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2024-config.yaml
        node sdk-resources/postscript.js ./PSSailpoint/v2024

    - name: Build V2025 SDK
      shell: bash
      run: |
        rm -rf ./PSSailpoint/v2025
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2025.yaml \
          -g powershell -o PSSailpoint/v2025 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2025-config.yaml
        node sdk-resources/postscript.js ./PSSailpoint/v2025

    - name: Build V2026 SDK
      shell: bash
      run: |
        rm -rf ./PSSailpoint/v2026
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2026.yaml \
          -g powershell -o PSSailpoint/v2026 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2026-config.yaml
        node sdk-resources/postscript.js ./PSSailpoint/v2026

    - name: Run Build Scripts
      shell: pwsh
      run: |
        $DebugPreference = "Continue"
        ./PSSailpoint/Build.ps1
        ./PSSailpoint/v3/Build.ps1
        ./PSSailpoint/beta/Build.ps1
        ./PSSailpoint/v2024/Build.ps1
        ./PSSailpoint/v2025/Build.ps1
        ./PSSailpoint/v2026/Build.ps1

    - name: Import Modules and Run Tests
      shell: pwsh
      run: |
        $DebugPreference = "Continue"
        Import-Module -Name '.\PSSailpoint\v3\src\PSSailpoint.V3' -Verbose
        Import-Module -Name '.\PSSailpoint\beta\src\PSSailpoint.Beta' -Verbose
        Import-Module -Name '.\PSSailpoint\v2024\src\PSSailpoint.V2024' -Verbose
        Import-Module -Name '.\PSSailpoint\v2025\src\PSSailpoint.V2025' -Verbose
        Import-Module -Name '.\PSSailpoint\v2026\src\PSSailpoint.V2026' -Verbose
        . .\PSSailpoint\Configuration.ps1
        . .\PSSailpoint\Pagination.ps1
        if ("${{ inputs.skip-tests }}" -ne "true") {
          Install-Module -Name Pester -Force
          Invoke-Pester -Output Detailed ./PSSailpoint/tests/
        }
