#
# Identity Security Cloud Beta API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: 3.1.0-beta
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'Tm.Beta' -name 'BetaVendorConnectorMapping' {
    Context 'BetaVendorConnectorMapping' {
        It 'Initialize-BetaVendorConnectorMapping' {
            # a simple test to create an object
            #$NewObject = Initialize-BetaVendorConnectorMapping -Id "TEST_VALUE" -Vendor "TEST_VALUE" -Connector "TEST_VALUE" -CreatedAt "TEST_VALUE" -CreatedBy "TEST_VALUE" -UpdatedAt "TEST_VALUE" -UpdatedBy "TEST_VALUE" -DeletedAt "TEST_VALUE" -DeletedBy "TEST_VALUE"
            #$NewObject | Should -BeOfType VendorConnectorMapping
            #$NewObject.property | Should -Be 0
        }
    }
}
