#
# Identity Security Cloud v2026 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2026
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.V2026' -name 'V2026V2026ApprovalsApi' {
    Context 'Approve-V2026Approval' {
        It 'Test Approve-V2026Approval' {
            #$TestResult = Approve-V2026Approval -Id "TEST_VALUE" -ApprovalApproveRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Approve-V2026ApprovalInBulk' {
        It 'Test Approve-V2026ApprovalInBulk' {
            #$TestResult = Approve-V2026ApprovalInBulk -BulkApproveRequestDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Suspend-V2026Approval' {
        It 'Test Suspend-V2026Approval' {
            #$TestResult = Suspend-V2026Approval -BulkCancelRequestDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-V2026ApprovalConfigRequest' {
        It 'Test Remove-V2026ApprovalConfigRequest' {
            #$TestResult = Remove-V2026ApprovalConfigRequest -Id "TEST_VALUE" -Scope "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026Approval' {
        It 'Test Get-V2026Approval' {
            #$TestResult = Get-V2026Approval -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026Approvals' {
        It 'Test Get-V2026Approvals' {
            #$TestResult = Get-V2026Approvals -Mine "TEST_VALUE" -RequesterId "TEST_VALUE" -RequesteeId "TEST_VALUE" -ApproverId "TEST_VALUE" -Count "TEST_VALUE" -CountOnly "TEST_VALUE" -IncludeComments "TEST_VALUE" -IncludeApprovers "TEST_VALUE" -IncludeBatchInfo "TEST_VALUE" -Filters "TEST_VALUE" -Limit "TEST_VALUE" -Offset "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026ApprovalsConfig' {
        It 'Test Get-V2026ApprovalsConfig' {
            #$TestResult = Get-V2026ApprovalsConfig -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Move-V2026Approval' {
        It 'Test Move-V2026Approval' {
            #$TestResult = Move-V2026Approval -BulkReassignRequestDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Send-V2026ApprovalsConfig' {
        It 'Test Send-V2026ApprovalsConfig' {
            #$TestResult = Send-V2026ApprovalsConfig -Id "TEST_VALUE" -Scope "TEST_VALUE" -ApprovalConfig "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Deny-V2026Approval' {
        It 'Test Deny-V2026Approval' {
            #$TestResult = Deny-V2026Approval -Id "TEST_VALUE" -ApprovalRejectRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Deny-V2026ApprovalInBulk' {
        It 'Test Deny-V2026ApprovalInBulk' {
            #$TestResult = Deny-V2026ApprovalInBulk -BulkRejectRequestDTO "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026ApprovalsAttributes' {
        It 'Test Update-V2026ApprovalsAttributes' {
            #$TestResult = Update-V2026ApprovalsAttributes -Id "TEST_VALUE" -ApprovalAttributesRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026ApprovalsComments' {
        It 'Test Update-V2026ApprovalsComments' {
            #$TestResult = Update-V2026ApprovalsComments -Id "TEST_VALUE" -ApprovalCommentsRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026ApprovalsReassign' {
        It 'Test Update-V2026ApprovalsReassign' {
            #$TestResult = Update-V2026ApprovalsReassign -Id "TEST_VALUE" -ApprovalReassignRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
