#
# Identity Security Cloud v2026 API
# Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
# Version: v2026
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSailpoint.V2026' -name 'V2026V2026GlobalTenantSecuritySettingsApi' {
    Context 'New-V2026AuthOrgNetworkConfig' {
        It 'Test New-V2026AuthOrgNetworkConfig' {
            #$TestResult = New-V2026AuthOrgNetworkConfig -NetworkConfiguration "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026AuthOrgLockoutConfig' {
        It 'Test Get-V2026AuthOrgLockoutConfig' {
            #$TestResult = Get-V2026AuthOrgLockoutConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026AuthOrgNetworkConfig' {
        It 'Test Get-V2026AuthOrgNetworkConfig' {
            #$TestResult = Get-V2026AuthOrgNetworkConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026AuthOrgServiceProviderConfig' {
        It 'Test Get-V2026AuthOrgServiceProviderConfig' {
            #$TestResult = Get-V2026AuthOrgServiceProviderConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-V2026AuthOrgSessionConfig' {
        It 'Test Get-V2026AuthOrgSessionConfig' {
            #$TestResult = Get-V2026AuthOrgSessionConfig
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026AuthOrgLockoutConfig' {
        It 'Test Update-V2026AuthOrgLockoutConfig' {
            #$TestResult = Update-V2026AuthOrgLockoutConfig -JsonPatchOperation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026AuthOrgNetworkConfig' {
        It 'Test Update-V2026AuthOrgNetworkConfig' {
            #$TestResult = Update-V2026AuthOrgNetworkConfig -JsonPatchOperation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026AuthOrgServiceProviderConfig' {
        It 'Test Update-V2026AuthOrgServiceProviderConfig' {
            #$TestResult = Update-V2026AuthOrgServiceProviderConfig -JsonPatchOperation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-V2026AuthOrgSessionConfig' {
        It 'Test Update-V2026AuthOrgSessionConfig' {
            #$TestResult = Update-V2026AuthOrgSessionConfig -JsonPatchOperation "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
