name: "Push PowerShell SDK Docs to Developer Portal"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_spec_workflow:
    name: Push API spec changes
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: powershell-sdk

      # Checkout the main branch of the developer portal to push changes
      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/developer.sailpoint.com
          path: developer-community
          ref: main

      - name: Install rsync
        run: |
          sudo apt install rsync grsync
      - name: Sync files between folders
        run: |
          CURRENT_V3_CODE_EXAMPLES_PATH="powershell-sdk/PSSailpoint/v3/docs/Examples/code_examples_overlay.yaml"
          NEW_V3_CODE_EXAMPLES_PATH="developer-community/static/code-examples/v3"
          CURRENT_V3_SPEC_PATH_METHODS="powershell-sdk/PSSailpoint/v3/docs/Methods"
          NEW_V3_API_SPEC_PATH_METHODS="developer-community/docs/tools/sdk/powershell/Reference/V3/Methods"
          CURRENT_V3_SPEC_PATH_MODELS="powershell-sdk/PSSailpoint/v3/docs/Models"
          NEW_V3_API_SPEC_PATH_MODELS="developer-community/docs/tools/sdk/powershell/Reference/V3/Models"



          CURRENT_BETA_CODE_EXAMPLES_PATH="powershell-sdk/PSSailpoint/beta/docs/Examples/code_examples_overlay.yaml"
          NEW_BETA_CODE_EXAMPLES_PATH="developer-community/static/code-examples/beta"
          CURRENT_BETA_SPEC_PATH_METHODS="powershell-sdk/PSSailpoint/beta/docs/Methods"
          NEW_BETA_API_SPEC_PATH_METHODS="developer-community/docs/tools/sdk/powershell/Reference/Beta/Methods"
          CURRENT_BETA_SPEC_PATH_MODELS="powershell-sdk/PSSailpoint/beta/docs/Models"
          NEW_BETA_API_SPEC_PATH_MODELS="developer-community/docs/tools/sdk/powershell/Reference/Beta/Models"


          CURRENT_V2024_CODE_EXAMPLES_PATH="powershell-sdk/PSSailpoint/v2024/docs/Examples/code_examples_overlay.yaml"
          NEW_V2024_CODE_EXAMPLES_PATH="developer-community/static/code-examples/v2024"
          CURRENT_V2024_SPEC_PATH_METHODS="powershell-sdk/PSSailpoint/v2024/docs/Methods"
          NEW_V2024_API_SPEC_PATH_METHODS="developer-community/docs/tools/sdk/powershell/Reference/V2024/Methods"
          CURRENT_V2024_SPEC_PATH_MODELS="powershell-sdk/PSSailpoint/v2024/docs/Models"
          NEW_V2024_API_SPEC_PATH_MODELS="developer-community/docs/tools/sdk/powershell/Reference/V2024/Models"

          rsync -cav --delete $CURRENT_V3_SPEC_PATH_METHODS $NEW_V3_API_SPEC_PATH_METHODS 
          rsync -cav --delete $CURRENT_BETA_SPEC_PATH_METHODS $NEW_BETA_API_SPEC_PATH_METHODS
          rsync -cav --delete $CURRENT_V2024_SPEC_PATH_METHODS $NEW_V2024_API_SPEC_PATH_METHODS
          rsync -cav --delete $CURRENT_V3_SPEC_PATH_MODELS $NEW_V3_API_SPEC_PATH_MODELS
          rsync -cav --delete $CURRENT_BETA_SPEC_PATH_MODELS $NEW_BETA_API_SPEC_PATH_MODELS
          rsync -cav --delete $CURRENT_V2024_SPEC_PATH_MODELS $NEW_V2024_API_SPEC_PATH_MODELS
          rsync -cav --delete $CURRENT_V3_CODE_EXAMPLES_PATH $NEW_V3_CODE_EXAMPLES_PATH
          rsync -cav --delete $CURRENT_BETA_CODE_EXAMPLES_PATH $NEW_BETA_CODE_EXAMPLES_PATH
          rsync -cav --delete $CURRENT_V2024_CODE_EXAMPLES_PATH $NEW_V2024_CODE_EXAMPLES_PATH
          cd developer-community
          git status
          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "devrel-service@sailpoint.com"
          git config --local user.name "developer-relations-sp"
          git add .
          git commit -m "Update to powershell SDK docs: ${{ github.run_id }}"
          git status
          git remote set-url origin https://${{secrets.DEVREL_SERVICE_TOKEN}}@github.com/sailpoint-oss/developer.sailpoint.com.git
          
          git remote -v
          git push